import { useQuery } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { api } from "../api";
import { GlassCard } from "../components/GlassCard";

export function UsersPage(){const {data,isLoading}=useQuery({queryKey:["users"],queryFn:api.users});return <Page title="Users" eyebrow="USER MANAGEMENT"><div className="table-card glass-card">{isLoading?"Loading…":<table><thead><tr><th>Name</th><th>Username</th><th>Department</th><th>Role</th><th>Status</th></tr></thead><tbody>{data?.users.map(u=><tr key={u.id}><td>{u.fullName}</td><td>{u.username}</td><td>{u.department??"—"}</td><td>{u.role}</td><td><span className={`status ${u.isActive?"published":"ended"}`}>{u.isActive?"ACTIVE":"INACTIVE"}</span></td></tr>)}</tbody></table>}</div></Page>}
export function StaffPage(){const {data,isLoading}=useQuery({queryKey:["staff"],queryFn:api.staff});return <Page title="Staff" eyebrow="STAFF MANAGEMENT"><div className="table-card glass-card">{isLoading?"Loading…":<table><thead><tr><th>Name</th><th>Username</th><th>Permissions</th><th>Status</th></tr></thead><tbody>{data?.staff.map(s=><tr key={s.id}><td>{s.fullName}</td><td>{s.username}</td><td>{s.permissions.join(", ")||"None"}</td><td>{s.isActive?"ACTIVE":"INACTIVE"}</td></tr>)}</tbody></table>}</div></Page>}
export function AnalyticsPage(){const {data}=useQuery({queryKey:["analytics"],queryFn:api.analytics});return <Page title="Analytics" eyebrow="PERFORMANCE"><div className="stats-grid">{Object.entries(data?.overview??{}).map(([k,v])=><GlassCard key={k}><small>{k}</small><strong>{v}</strong></GlassCard>)}</div><div className="table-card glass-card"><h3>Recent quizzes</h3><table><tbody>{data?.topQuizzes.map(q=><tr key={q.id}><td>{q.title}</td><td>{q.subject}</td><td>{q.status}</td></tr>)}</tbody></table></div></Page>}
export function ActivityPage(){const {data}=useQuery({queryKey:["activity"],queryFn:api.activity});return <Page title="Activity Logs" eyebrow="AUDIT TRAIL"><div className="table-card glass-card"><table><thead><tr><th>Action</th><th>User</th><th>IP</th><th>Time</th></tr></thead><tbody>{data?.logs.map(l=><tr key={l.id}><td>{l.action}</td><td>{l.user?.username??"system"}</td><td>{l.ipAddress??"—"}</td><td>{new Date(l.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div></Page>}
function Page({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <div><div className="hero-row"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div></div>{children}</div>}
