import {Router} from 'express'; import rateLimit from 'express-rate-limit'; import {login,logout,me} from '../controllers/auth.controller.js'; import * as users from '../controllers/users.controller.js'; import * as staff from '../controllers/staff.controller.js'; import * as quizzes from '../controllers/quizzes.controller.js'; import * as participant from '../controllers/participant.controller.js'; import * as analytics from '../controllers/analytics.controller.js'; import {qr} from '../controllers/qr.controller.js'; import {requireAuth,requirePermission,requireRole} from '../middleware/auth.js';
const r=Router(); const loginLimiter=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false});
r.post('/auth/login',loginLimiter,login); r.post('/auth/logout',requireAuth,logout); r.get('/auth/me',requireAuth,me);
r.get('/users',requireAuth,requireRole('SUPER_ADMIN'),users.list); r.get('/users/:id',requireAuth,requireRole('SUPER_ADMIN'),users.get); r.post('/users',requireAuth,requireRole('SUPER_ADMIN'),users.create); r.patch('/users/:id',requireAuth,requireRole('SUPER_ADMIN'),users.update); r.delete('/users/:id',requireAuth,requireRole('SUPER_ADMIN'),users.remove);
r.get('/staff',requireAuth,requireRole('SUPER_ADMIN'),staff.list); r.post('/staff',requireAuth,requireRole('SUPER_ADMIN'),staff.create); r.delete('/staff/:id',requireAuth,requireRole('SUPER_ADMIN'),staff.remove); r.patch('/staff/:id/permissions',requireAuth,requireRole('SUPER_ADMIN'),staff.permissions);
r.get('/quizzes',requireAuth,quizzes.list); r.get('/quizzes/:id',requireAuth,quizzes.get); r.post('/quizzes',requireAuth,requirePermission('CREATE_QUIZ'),quizzes.create); r.patch('/quizzes/:id',requireAuth,requirePermission('EDIT_QUIZ'),quizzes.update); r.delete('/quizzes/:id',requireAuth,requirePermission('DELETE_QUIZ'),quizzes.remove); r.post('/quizzes/:id/publish',requireAuth,requirePermission('EDIT_QUIZ'),quizzes.publish); r.post('/quizzes/:id/start',requireAuth,requirePermission('START_QUIZ'),quizzes.start); r.post('/quizzes/:id/end',requireAuth,requirePermission('END_QUIZ'),quizzes.end); r.post('/quizzes/:id/questions',requireAuth,requirePermission('EDIT_QUIZ'),quizzes.addQuestion); r.get('/quizzes/:quizId/leaderboard',participant.leaderboard); r.get('/quizzes/:quizId/qr/:joinCode',requireAuth,requirePermission('START_QUIZ'),qr);
r.post('/join/:joinCode',participant.join); r.get('/participant/session/:sessionId',participant.session); r.post('/participant/session/:sessionId/answer',participant.answer); r.post('/participant/session/:sessionId/complete',participant.complete); r.get('/participant/session/:sessionId/result',participant.result);
r.get('/admin/analytics',requireAuth,requireRole('SUPER_ADMIN'),analytics.dashboard); r.get('/admin/activity',requireAuth,requireRole('SUPER_ADMIN'),analytics.activity);
export default r;
