import {Request,Response} from 'express'; import {prisma} from '../config/prisma.js'; import {quizSchema,questionSchema} from '../validators/quiz.js'; import {uniqueCode} from '../services/quiz.service.js'; import {logActivity} from '../utils/activity.js';
export async function list(req:Request,res:Response){const items=await prisma.quiz.findMany({include:{_count:{select:{questions:true,participants:true}}},orderBy:{updatedAt:'desc'}});res.json({success:true,items})}
export async function get(req:Request,res:Response){const quiz=await prisma.quiz.findUnique({where:{id:req.params.id},include:{questions:{include:{options:true},orderBy:{order:'asc'}},_count:{select:{participants:true}}}});if(!quiz)return res.status(404).json({success:false,message:'Quiz not found.'});res.json({success:true,quiz})}
export async function create(req:Request,res:Response){const body=quizSchema.parse(req.body);const quiz=await prisma.quiz.create({data:{...body,joinCode:await uniqueCode(),createdById:req.user!.id}});await logActivity({userId:req.user!.id,action:'CREATE_QUIZ',targetType:'Quiz',targetId:quiz.id});res.status(201).json({success:true,quiz})}
export async function update(req:Request,res:Response){const body=quizSchema.partial().parse(req.body);const quiz=await prisma.quiz.update({where:{id:req.params.id},data:body});await logActivity({userId:req.user!.id,action:'EDIT_QUIZ',targetType:'Quiz',targetId:quiz.id});res.json({success:true,quiz})}
export async function remove(req:Request,res:Response){const quiz=await prisma.quiz.update({where:{id:req.params.id},data:{status:'ARCHIVED'}});await logActivity({userId:req.user!.id,action:'DELETE_QUIZ',targetType:'Quiz',targetId:quiz.id});res.json({success:true})}
export async function publish(req:Request,res:Response){const quiz=await prisma.quiz.update({where:{id:req.params.id},data:{status:'PUBLISHED'}});await logActivity({userId:req.user!.id,action:'PUBLISH_QUIZ',targetType:'Quiz',targetId:quiz.id});res.json({success:true,quiz})}
export async function start(req:Request,res:Response){const quiz=await prisma.quiz.update({where:{id:req.params.id},data:{status:'LIVE',startTime:new Date()}});await prisma.quizSession.create({data:{quizId:quiz.id,startedAt:new Date()}});await logActivity({userId:req.user!.id,action:'START_QUIZ',targetType:'Quiz',targetId:quiz.id});res.json({success:true,quiz})}
export async function end(req:Request,res:Response){const quiz=await prisma.quiz.update({where:{id:req.params.id},data:{status:'ENDED',endTime:new Date()}});await prisma.quizSession.updateMany({where:{quizId:quiz.id,endedAt:null},data:{endedAt:new Date()}});await logActivity({userId:req.user!.id,action:'END_QUIZ',targetType:'Quiz',targetId:quiz.id});res.json({success:true,quiz})}
export async function addQuestion(req:Request,res:Response){
  const body=questionSchema.parse(req.body);
  const quiz=await prisma.quiz.findUnique({where:{id:req.params.id}});
  if(!quiz)return res.status(404).json({success:false,message:'Quiz not found.'});
  const question=await prisma.question.create({data:{quizId:quiz.id,questionText:body.questionText,questionType:body.questionType,points:body.points,timeLimit:body.timeLimit,explanation:body.explanation,order:await prisma.question.count({where:{quizId:quiz.id}}),options:{create:body.options}}});
  res.status(201).json({success:true,question});
}
